import { Amiri } from "next/font/google";
import dynamic from "next/dynamic";
import "./globals.css";
import Header from "@/components/Header";

import ToastProvider from "@/lib/toast/ToastProvider";

const StoreProvider = dynamic(() => import("@/redux/StoreProvider"), {
  ssr: false,
});
const inter = Amiri({
  subsets: ["arabic"],
  display: "swap",
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full bg-white `}>
        <ToastProvider>
          <StoreProvider>
            <Header />

            <div className="max-w-[1200px] mx-auto grid">{children}</div>
          </StoreProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
